name: Federated Learning

on:
  push:
    branches: [ "master", "main", "develop" ]
    paths:
      - src/federated-learning/**
      - .github/workflows/federated-learning.yml
  pull_request:
    branches: [ "master", "main", "develop" ]
    paths:
      - src/federated-learning/**
      - .github/workflows/federated-learning.yml

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/federated-learning/docs/requirements.txt

      - name: Run tests
        run: |
          pytest src/federated-learning/tests

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 src/federated-learning/fed-models/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/federated-learning/tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics